/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ultils;

/**
 *
 * @author Minh-PC
 */
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
  
// Java program to calculate MD5 hash value
public class MD5 {
    public  String getMd5(String input)
    {
        try {
  
            //Phương thức tatic getInstance được gọi với băm MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
  
         //phương thức digan () được gọi để tính toán thông báo tóm tắt
             // của một thông báo đầu vào () trả về mảng byte
            byte[] messageDigest = md.digest(input.getBytes());
  
            // Chuyển mảng byte thành biểu diễn dấu hiệu
            BigInteger no = new BigInteger(1, messageDigest);
  
            // Convert message digest into hex value
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } 
  
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
  
    // Driver code
    public static void main(String args[]) throws NoSuchAlgorithmException
    {
        //698d51a19d8a121ce581499d7b701668
        //d9b1d7db4cd6e70935368a1efb10e377
        //d9b1d7db4cd6e70935368a1efb10e377
        String s = "123";
        MD5 a = new MD5();
        System.out.println("Your HashCode Generated by MD5 is: " + a.getMd5(s));
    }
}